---
title: "R을 이용한 데이터 전처리 숙제 3"
author: "waterfirst"
format:
  html:
    toc: true
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
editor: visual
code-fold: false
Rendering:
  embed-resources: true
execute:
  message: false
  warning: false
  error: false
  echo: true
lightbox: true
---

## 1 여러 엑셀데이터 한번에 불러오기

```         
 [1] "1952.xlsx" "1957.xlsx" "1962.xlsx" "1967.xlsx"
 [5] "1977.xlsx" "1982.xlsx" "1987.xlsx" "1992.xlsx"
 [9] "1997.xlsx" "2002.xlsx" "2007.xlsx"
```

-   11개의 엑셀파일을 하나의 dataframe 으로 만든 후 대륙별로 연도별 기대수명을 라인, 산점도 그래프로 보이시오.

```{r}
#| echo: false

library(tidyverse)
library(ggrepel)
library(readxl)
library(purrr)

setwd("D:/r/유형별 r 예제/Data_visualization")


paths <- list.files("data/gapminder", pattern = "[.]xlsx$", full.names = TRUE)


gapminder <- paths |> 
  set_names(basename) |> 
  map(read_excel) |> 
  list_rbind(names_to = "year") |> 
  mutate(year = parse_number(year))

gapminder |> 
 group_by(year, continent) |> summarise(기대수명 = mean(lifeExp, na.rm=T)) |> 
 ggplot(aes(x=year, y=기대수명, col=continent,group = continent))+
  geom_point()+geom_line()+
    geom_label_repel(aes(label = ifelse(year == max(year), continent, "")),
                   nudge_x = 1,
                   na.rm = TRUE)+
  theme_bw()

```

## 2 엑셀안에 여러 시트 한번에 불러오기

```         
$file
[1] "D:/r/유형별 r 예제/Data_visualization/data/gapmider.xlsx"

$sheet
 [1] "1952" "1957" "1962" "1967" "1977" "1982" "1987" "1992" "1997" "2002" "2007"
```

-   11개의 시트를 불러와서 year 변수에 시트이름을 넣고, 대륙별로 연도별 기대수명 증가 그래프를 ggridges 패키지를 이용하여 그리시오. (오세아니아 제외)

\[참고하세요\]<https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html>

```{r}
#| echo: false


library(readxl)
library(purrr)

setwd("D:/r/유형별 r 예제/Data_visualization/data/")

file_1<- structure(list(file = c("D:/r/유형별 r 예제/Data_visualization/data/gapmider.xlsx"), sheet = excel_sheets("gapmider.xlsx")))

df <- map2(file_1$file, file_1$sheet, ~ read_excel(path = .x, sheet = .y, range = "A1:E143")) %>%
  list_rbind(names_to = "year") %>%
  mutate(year = rep(c(file_1$sheet), each = n()/length(file_1$sheet)))


library(ggridges)
library(tidyverse)
library(tidyquant)
library(showtext) # 한글
showtext_auto()

df |> 
  filter(continent !="Oceania") |> 
  ggplot(aes(x = lifeExp, y = year, fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis_c(name = "수명[세]", option = "C") +
  facet_wrap(~continent,)+
  labs(title = '대륙별로 연도에 따른 기대 수명 증가 그래프',
       x = "기대수명", y="연도")


```
